### ISSUE TITLE
Alternating Colours CSS for disabled treeview

### ISSUE THREAD

**Issue by luigifab** [lah7/gtk3-mushrooms#120]
### Bug Description

It looks like that it's not possible to set alternating background color when caja treeview is disabled.

```css
window.caja-navigation-window notebook.caja-notebook scrolledwindow.frame treeview.view:disabled {
	background-color: lighter(darker(@theme_base));
}
window.caja-navigation-window notebook.caja-notebook scrolledwindow.frame treeview.view.odd,
window.caja-navigation-window notebook.caja-notebook scrolledwindow.frame treeview.view.odd.sorted {
	background-color: yellow;
}
window.caja-navigation-window notebook.caja-notebook scrolledwindow.frame treeview.view.odd:disabled,
window.caja-navigation-window notebook.caja-notebook scrolledwindow.frame treeview.view.odd.sorted:disabled {
	background-color: orange;
}
```

### Expected Behaviour

Allow to set background color for odd and even rows.

### Screenshots

Maybe it's due to caja?
![Image](https://github.com/user-attachments/assets/fcf6386d-8ec9-4734-b6a9-4a1c7b88c365)

But maybe no?
![Image](https://github.com/user-attachments/assets/0a623f0b-6ab7-46b6-8f75-f5b52071c5b4)

### Operating System

Debian Testing and Fedora Rawhide

### Desktop Environment

MATE

### gtk3-classic Version

3.24.49

**Comment by lah7** [comment]
How do you reproduce the disabled state in a Caja list view?

That looks like an 'inactive' state (if `GTK_BACKDROP=1` is set, maybe?). I couldn't reproduce this with the Breeze GTK theme, but I reckon it could be due to the GTK theme used.

**Comment by luigifab** [comment]
F3

**Comment by lah7** [comment]
Still can't reproduce here, or with the [Ambiant-MATE](https://github.com/lah7/Ambiant-MATE) theme. The alternating colours stays intact.

![Screenshot_20250329_160749](https://github.com/user-attachments/assets/7bb421af-f6c9-4792-801f-6a554685c3b3)
![Screenshot_20250329_161023](https://github.com/user-attachments/assets/bd5cc61a-2c48-4b00-a486-adf2695c5d8a)

Technically, looking at the [GTK Debugger](https://github.com/lah7/gtk3-classic/wiki/Debugging-GTK), `is-focus` changes. I don't think the treeview is disabled.

Looking at your code, your CSS overrides the generic GTK code by specifically picking Caja's classes. We recommend [styling treeviews generically.](https://github.com/lah7/gtk3-classic/wiki/Treeview:-Alternating-Colours-CSS)

Your CSS example continues to show the yellow alternating rows on the other side, with Ambiant-MATE or Breeze's GTK theme:

![Screenshot_20250329_161600](https://github.com/user-attachments/assets/bbbdcc49-72d1-4fa2-90d2-31acaea6c41b)

Looks like a CSS issue with the theme you're using. I don't see any problems with the patch enabling the functionality.

**Comment by luigifab** [comment]
Hum, I don't see the orange background color for the disabled view in your screenshot, anyway, for me it's only white (or grey below). Here is another example with only the following CSS code in gtk.css:

```css
treeview.view {
    background-color: cyan;
}
treeview.view.odd {
    background-color: yellow;
}
treeview.view.even {
    background-color: blue;
}
treeview.view:selected {
    background-color: red;
    color: orange;
}
treeview.view:disabled {
    background-color: gray;
}
treeview.view.odd:disabled,
treeview.view.even:disabled,
treeview.view:selected:disabled {
    background-color: lime;
}
```

![Image](https://github.com/user-attachments/assets/cff08689-d725-4e13-8986-74905a36ae58)

Yes I'm using GTK_BACKDROP=1 with Caja 1.26.
Do you think it's the problem?

----

Debian Testing with Caja 1.26, without gtk3-classic:

![Image](https://github.com/user-attachments/assets/3a7b8af4-cd59-48a9-b114-a8a8f9ea18ec)

Fedora Rawhide with Caja 1.28, without gtk3-classic:

![Image](https://github.com/user-attachments/assets/259be3b2-552d-4768-abd8-e8c809fd633f)

**Comment by luigifab** [comment]
lol, this is working (with gtk3-classic):

```css
treeview.view {
    background: linear-gradient(to bottom, cyan, cyan);
}
treeview.view.odd {
    background: linear-gradient(to bottom, yellow, yellow);
}
treeview.view.even {
    background: linear-gradient(to bottom, blue, blue);
}
treeview.view:selected {
    background: linear-gradient(to bottom, red, red);
    color: orange;
}
```

![Image](https://github.com/user-attachments/assets/e34fe623-cc45-4ee9-b0e6-3eb186c77566)


So, (without gtk3-classic), what is this shit?

![Image](https://github.com/user-attachments/assets/b221c01a-0bf0-42f0-aeb9-2a6eee684b93)
