### ISSUE TITLE
Request: Text color in progress bar

### ISSUE THREAD

**Issue by luigifab** [lah7/gtk3-mushrooms#58]
### What should be patched?

Perhaps for good reasons, GTK has moved the progress text outside the progress bar.
(the double text color still works with progress bars in treeviews)

I suggest to add something like: `GTK_PROGRESS_TEXT_INSIDE=1`.
When this environment variable exists:
- add the progress text inside the progress bar,
- add a new CSS class to the progress bar,
- and allow the text to get two colors.

How? I don't know, I found how to put the text inside the progress bar, and how to add a CSS class to the progress bar. But for the colors... [Draft](https://gist.github.com/luigifab/0fce786cdb93b5687069a82f490ea95e).

### Screenshots

Ambiance theme with Ubuntu 11.10 - GTK 3.2:
![image](https://user-images.githubusercontent.com/31816829/120078122-33277b00-c0ae-11eb-80da-d504ad03be7d.png)

Ambiance theme with Ubuntu 13.04 - GTK 3.6:
![image](https://user-images.githubusercontent.com/31816829/120078133-43d7f100-c0ae-11eb-9582-649b09ca639f.png)

Ambiance theme with Ubuntu 13.10 - GTK 3.8:
![image](https://user-images.githubusercontent.com/31816829/120078318-366f3680-c0af-11eb-878d-f21b181380fe.png)

My theme with GTK 3.24 (without any GTK changes):
![image](https://user-images.githubusercontent.com/31816829/150101871-7c886b7a-da55-48bd-9e16-8c597c60a59c.png)

### Commits

The old method, GTK 3.6: [gtk_progress_bar_paint_text](https://github.com/GNOME/gtk/blob/20db44f587d6ae180366339673dc45265133a36c/gtk/gtkprogressbar.c#L822)
The new method (not sure), GTK 3.24: [gtk_progress_bar_render_text](https://github.com/GNOME/gtk/blob/3.24.31/gtk/gtkprogressbar.c#L1313)

For progress bar in treeview, the method (not sure), GTK 3.24: [gtk_cell_renderer_progress_render](https://github.com/GNOME/gtk/blob/3.24.30/gtk/gtkcellrendererprogress.c#L645)

**Comment by luigifab** [comment]
I tried some ideas ([appearance__progress_text.patch](https://gist.github.com/luigifab/0fce786cdb93b5687069a82f490ea95e)).

I think the idea is simple:
- draw the text for "left part"
- draw the text for "right part"
- draw texts at the same position
- next, texts must be clipped (according the position of the progress bar)

For now, the patch doesn't calculate clip position/size correctly...

**Comment by lah7** [comment]
You may be interested in the code for this patch that was going to introduce this classic style of progress bar to the MATE shut down / log out dialog:

* https://github.com/mate-desktop/mate-session-manager/pull/261

**Comment by luigifab** [comment]
Yolo! done for gtk3! horizontal! vertical! ltr! rtl!

![image](https://github.com/lah7/gtk3-classic/assets/31816829/dacaa574-53cc-488d-8191-918bbec6eda0) ![image](https://github.com/lah7/gtk3-classic/assets/31816829/18c71697-b65d-4d05-a0fa-dc175ff1495d)

for gtk3: todo: automatic width/height without min-width/height from css theme + position of the text
for gtk4: new fight in progress

**Comment by luigifab** [comment]
Alright for GTK 3! ... (with chatGPTpro and me)
I have a degree in design:

```css
progressbar,
progressbar text,
progressbar trough,
progressbar progress {
	margin: 0;
	padding: 0;
	min-width: 0;
	min-height: 0;
}
progressbar {
	background: cyan;
}
progressbar trough {
	background: black;
}
progressbar progress {
	background: white;
}
progressbar.empty trough {
	background: orange;
}
progressbar.full progress {
	background: gold;
}
progressbar text {
	font-size: 25px;
}
progressbar.classic text.trough {
	color: yellow;
}
progressbar.classic text.progress {
	color: blue;
}
```

Result (**gtk3**) without text (img1) + with text without (img2) and with (img3) `GTK_PROGRESS_TEXT_INSIDE=1` :

![Image](https://github.com/user-attachments/assets/90880d47-b224-4d5e-97d1-ee7733044a64) ![Image](https://github.com/user-attachments/assets/6e0b01da-13f5-4c8f-8d53-3bdc65af40a6) ![Image](https://github.com/user-attachments/assets/e5411e33-2aab-4a89-8df4-d581be44a42f)

[Love me](https://build.opensuse.org/package/show/home:luigifab/gtk3-classic), it's free!

**Comment by luigifab** [comment]
Alright for GTK 4! ... (with chatGPTpro and chatGPT and me, but... chatGPT was very bad)

Automatic width/height from text does not work, and it's necessary to hide the original text.
Moreover, without the patch, to prevent people from displaying the label above the progress bar, gtk4 devs have changed its position in the widget (compared to gtk3), so when negative margins are applied, the label ends up under the progress bar, and it is invisible.

I have a degree in design:
```css
progressbar,
progressbar text,
progressbar trough,
progressbar progress {
	margin: 0;
	padding: 0;
	min-width: 0;
	min-height: 0;
	font-size: 25px;
}
progressbar {
	background: cyan;
}
progressbar trough {
	background: black;
}
progressbar progress {
	background: white;
}
progressbar.empty trough {
	background: orange;
}
progressbar.full progress {
	background: gold;
}
progressbar text {
	color: orange;
}

/* @see https://github.com/GNOME/gtk/blob/013b629a2e5420cc01647f859226eb1a37ebe661/gtk/gtkprogressbar.c#L92 */
progressbar.horizontal,
progressbar.horizontal trough {
	min-width: 150px;
	min-height: 6px;
}
progressbar.horizontal progress {
	min-height: 6px;
}
progressbar.vertical,
progressbar.vertical trough {
	min-width: 7px;
	min-height: 80px;
}
progressbar.vertical progress {
	min-width: 7px;
}

/* for the patch */
progressbar.horizontal trough,
progressbar.horizontal progress {
	min-height: 25px;
}
progressbar.vertical trough,
progressbar.vertical progress {
	min-width: 80px;
}
progressbar.classic text {
	opacity: 0;
}
progressbar.classic .text.trough {
	color: yellow;
	font-size: 25px;
}
progressbar.classic .text.progress {
	color: blue;
	font-size: 25px;
}
```

Result (**gtk4**) without text (img1) + with text without (img2) and with (img3) `GTK_PROGRESS_TEXT_INSIDE=1` :

![Image](https://github.com/user-attachments/assets/a7ce82c1-f294-4807-86ef-fa4005bc7e8b) ![Image](https://github.com/user-attachments/assets/7bdff319-5dba-40ae-b4fa-9f6ae11a6fe6) ![Image](https://github.com/user-attachments/assets/a8e752b8-a5da-4f26-b40a-e18bb17e8e42)

[Love me](https://build.opensuse.org/package/show/home:luigifab/gtk4-classic), it's free!
